"""
SmartVisionOC Configuration Module
"""
import os


class Settings:
    APP_NAME: str = "SmartVisionOC"
    APP_TITLE: str = "SmartVisionOC: Explainable Multi-Modal AI Framework for Zero-Shot Industrial Quality Inspection"
    VERSION: str = "0.1.0-prototype"
    
    # Pluggable Inference Mode: "MOCK" | "TORCH_CUDA" | "ONNX"
    AI_INFERENCE_MODE: str = os.getenv("AI_INFERENCE_MODE", "MOCK")
    
    # Transparency Guarantee
    DISCLAIMER: str = (
        "SIMULATED MOCK INFERENCE: Results generated by deterministic algorithmic simulation "
        "for architectural testing and UI validation. Plug-in interfaces provided for live PyTorch/ONNX models."
    )
    
    # Default Risk and Decision Thresholds
    DEFAULT_PASS_THRESHOLD: float = 0.25
    DEFAULT_REJECT_THRESHOLD: float = 0.65
    DEFAULT_UNCERTAINTY_TOLERANCE: float = 0.40
    
    # Preprocessing Defaults
    DEFAULT_CLAHE_CLIP: float = 2.0
    DEFAULT_TILE_GRID: int = 8
    
    # Evidence Fusion Default Weights
    WEIGHT_VISUAL: float = 0.35
    WEIGHT_GEOMETRIC: float = 0.20
    WEIGHT_DEPTH: float = 0.30
    WEIGHT_OPERATOR: float = 0.15

settings = Settings()
